version: '3.9'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: volodya
      POSTGRES_PASSWORD: 1234
  adminer:
    image: adminer
    ports:
      - 8088:8080
  app:
    build: .
    environment:
      POSTGRES_USER: volodya
      POSTGRES_PASSWORD: 1234
    ports:
      - 80:80
    depends_on:
      - db
